### ISSUE TITLE
Google search is not working.

### ISSUE THREAD

**Issue by iamevs** [Rajaniraiyn/raj-browser#101]
## Google Search

- Only the search with the links are get opened.
- If anything is got searched in the engine that shows a empty page.

![image](https://user-images.githubusercontent.com/97862544/195013874-53fdcba5-d33d-4326-95b9-a49c54cbcf24.png)

![image](https://user-images.githubusercontent.com/97862544/195014136-c59553d7-acc0-46bd-841b-394906f19fc9.png)

**Comment by Rajaniraiyn** [comment]
Have you tried some other search sites like bing.com and duck.com ?

**Comment by Rajaniraiyn** [comment]
Will be fixed on next version release. Thanks for your time
