### ISSUE TITLE
Porting from <webview> to BrowserView for additional performance and security: really important!!!

### ISSUE THREAD

**Issue by raphael10-collab** [Rajaniraiyn/raj-browser#105]
I strongly advocate and kindly ask for this enhanced feature: 
    
    Porting from <webview> to BrowserView for additional performance and security

**Comment by Rajaniraiyn** [comment]
@raphael10-collab Thanks for your feedback. the v2 of the browser is completely rewritten using `BrowserView` for the mentioned reasons. The updated source will be published soon.

**Comment by raphael10-collab** [comment]
Thank you @Rajaniraiyn 

I'm looking forward to the update source

I'm happy to be "Beta Tester"

**Comment by Rajaniraiyn** [comment]
Thank you for your support. I'll update the source soon.

**Comment by Rajaniraiyn** [comment]
Fixed in 67bf2b08678db547469b8a938b2e066a4e7297fc, this implementation will be improved further
